import os

LOG_LEVEL = os.environ.get('LOG_LEVEL', 'INFO')

DYNAMODB_SESSION_TABLE_NAME = os.environ.get('DYNAMODB_SESSION_TABLE_NAME', None)
DYNAMODB_GAME_TABLE_NAME = os.environ.get('DYNAMODB_GAME_TABLE_NAME', None)
DYNAMODB_USER_TABLE_NAME = os.environ.get('DYNAMODB_USER_TABLE_NAME', None)
DYNAMODB_TTL_DAYS = os.environ.get('DYNAMODB_TTL_DAYS', 7)
WS_API_GATEWAY_URL = os.environ.get('WS_API_GATEWAY_URL', None)
